{% set name = "apache-airflow-providers-snowflake" %}
{% set version = "5.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_snowflake-{{ version }}.tar.gz
  sha256: 48c25cf44fca42dd53af9c3c8993d72021b6e7a8208013fdd94c2d8d1dd7d31b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<4.dev0
    - apache-airflow-providers-common-compat >=1.1.0
    - apache-airflow-providers-common-sql >=1.14.1
    - apache-airflow >=2.8.0
    # use the more constrained dependencies to stay noarch: python
    - pandas >=2.1.2,<2.2
    - pyarrow >=14.0.1
    - snowflake-connector-python >=3.7.1
    - snowflake-snowpark-python >=1.17.0
    - snowflake-sqlalchemy >=1.4.0

test:
  imports:
    - airflow.providers.snowflake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-snowflake for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/snowflake/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
