{% set name = "apache-airflow-providers-snowflake" %}
{% set version = "6.7.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_snowflake-{{ version }}.tar.gz
  sha256: 74b8b8255a85a4ebf65bd8752ae3192e7e6639a4ed02d7e130c8259b95d7b150

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.8.0
    - apache-airflow-providers-common-sql >=1.27.5
    # use the more constrained dependencies to stay noarch: python
    # https://github.com/apache/airflow/blob/providers-snowflake/{{ version }}/generated/provider_dependencies.json
    - pandas >=2.1.2
    - pyarrow >=16.1.0
    - snowflake-connector-python >=3.16.0
    - snowflake-sqlalchemy >=1.7.0
    # including for all python to stay noarch: python
    - snowflake-snowpark-python >=1.17.0,<9999
    - setuptools >=80.0.0,<9999

test:
  imports:
    - airflow.providers.snowflake
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-snowflake for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
