{% set name = "apache-airflow-providers-snowflake" %}
{% set version = "5.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_snowflake-{{ version }}.tar.gz
  sha256: 6a559f3b9706bdc1f2b63127c0384f78f101a806f069c6555a858e5932cdf380

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.10.0
    - apache-airflow >=2.6.0
    - snowflake-connector-python >=2.7.8
    - snowflake-sqlalchemy >=1.1.0

test:
  imports:
    - airflow.providers.snowflake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-snowflake for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/snowflake/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
