{% set name = "apache-airflow-providers-snowflake" %}
{% set version = "5.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_snowflake-{{ version }}.tar.gz
  sha256: bd2bd8680f387cfae8e23149691bd53d9cb061fb966b3767cac6aa43962c8ee7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.1
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow-providers-common-compat >=1.1.0
    - apache-airflow-providers-common-sql >=1.20.0
    - apache-airflow >=2.8.0
    # use the more constrained dependencies to stay noarch: python
    # https://github.com/apache/airflow/blob/providers-snowflake/{{ version }}/generated/provider_dependencies.json
    - pandas >=2.1.2,<2.2
    - pyarrow >=14.0.1
    - snowflake-connector-python >=3.7.1
    - snowflake-snowpark-python >=1.17.0
    - snowflake-sqlalchemy >=1.4.0

test:
  imports:
    - airflow.providers.snowflake
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-snowflake for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/snowflake/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
