{% set name = "apache-airflow-providers-snowflake" %}
{% set version = "5.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_snowflake-{{ version }}.tar.gz
  sha256: 6b64e62f08c70fd06b502114e738f0277b94f91e848701f0acf76fd4cb0a6c44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<4.dev0
    - apache-airflow-providers-common-compat >=1.1.0
    - apache-airflow-providers-common-sql >=1.14.1
    - apache-airflow >=2.7.0
    # use the more constrained dependencies to stay noarch: python
    # https://github.com/apache/airflow/blob/providers-snowflake/{{ version }}/generated/provider_dependencies.json
    - pandas >=2.1.2,<2.2
    - pyarrow >=14.0.1
    - snowflake-connector-python >=3.7.1
    - snowflake-sqlalchemy >=1.4.0

test:
  imports:
    - airflow.providers.snowflake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-snowflake for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/snowflake/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
