{% set name = "apache-airflow-providers-snowflake" %}
{% set version = "6.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_snowflake-{{ version }}.tar.gz
  sha256: 04ce97a87c1264b4b83dad3e1d391c5d704a4a37eb2113502d53ff5acf45c0da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.9.0
    - apache-airflow-providers-common-compat >=1.6.0
    - apache-airflow-providers-common-sql >=1.20.0
    # use the more constrained dependencies to stay noarch: python
    # https://github.com/apache/airflow/blob/providers-snowflake/{{ version }}/generated/provider_dependencies.json
    - pandas >=2.1.2,<2.2
    - pyarrow >=14.0.1
    - snowflake-connector-python >=3.7.1
    - snowflake-sqlalchemy >=1.4.0
    # including for all python to stay noarch: python
    - snowflake-snowpark-python >=1.17.0

test:
  imports:
    - airflow.providers.snowflake
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-snowflake for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file: src/airflow/providers/snowflake/LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
