context:
  name: apache-airflow-providers-snowflake
  version: 6.9.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_snowflake-${{ version }}.tar.gz
  sha256: 4108a2f2fbed1abd4a7c810d6795e9f9e405fd2a7b712cf18b2d47bedd30cdf2

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==3.12.0
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.12.0
    - apache-airflow-providers-common-sql >=1.27.5
    - pandas >=2.1.2
    - pyarrow >=16.1.0
    - snowflake-connector-python >=3.16.0
    - snowflake-sqlalchemy >=1.7.0
    - snowflake-snowpark-python >=1.17.0,<9999
    - setuptools >=80.0.0,<9999
tests:
  - python:
      imports:
        - airflow.providers.snowflake
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-snowflake for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
