context:
  name: apache-airflow-providers-snowflake
  version: "6.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_snowflake-${{ version }}.tar.gz
  sha256: 0ec6db5287853dce0c3b4a4b8b483f4b705fba80560be5399a63a39510318462

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==3.12.0
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.10.1
    - apache-airflow-providers-common-sql >=1.27.5
    # more restrictive for python >=3.13
    - pandas >=2.2.3
    # more restrictive for python >=3.13
    - pyarrow >=18.0.0
    - snowflake-connector-python >=3.16.0
    - snowflake-sqlalchemy >=1.7.0
    # more restrictive for python >=3.12
    - snowflake-snowpark-python >=1.27.0,<9999
    - setuptools >=80.0.0,<9999

tests:
  - python:
      imports:
      - airflow.providers.snowflake
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-snowflake for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
